### ISSUE TITLE
Problem with Environment Configuration: [RUN get_start.py with errors]

### ISSUE THREAD

**Issue by sxzhuang** [FuxiRL/DunkCityDynasty#1]
## My configuration
System: Ubuntu 20.04
The python version is `3.8.10`. I have successfully installed Wine using the instructions in `install_deps.sh`. I have also installed all packages from the `requirements.txt` file, except for `torch==1.11.0`, as I have already installed version 2.0.1 using pip.

Then, I modified line 20 in get_start.py as follows: 
```
    config = {
        'id': 1,
        'env_setting': 'linux',
        'client_path': 'path-to-game-client',
        'rl_server_ip': '127.0.0.1',
        'rl_server_port': 42636,
        'game_server_ip': 'according to the email sent to me',
        'game_server_port': according to the email sent to me,
        'machine_server_ip': '',
        'machine_server_port': 0,
        'episode_horizon': 100000,
        'user_name': 'according to the email sent to me'
    }
```

## Errors
When I run `python get_start.py`, the output is as follows:
```
0024:fixme:ntdll:create_logical_proc_info Improve CPU info reporting: system supports 48 logical cores, but only 32 supported!
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 33
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 34
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 35
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 36
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 37
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 38
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 39
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 40
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 41
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 42
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 43
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 44
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 45
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 46
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 47
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
wine: failed to open "path-to-game-client/Lx33.exe": c0000135
```

When I press ```Ctrl + C```, the output is as follows:
```
Traceback (most recent call last):
  File "get_start.py", line 74, in <module>
    main()
  File "get_start.py", line 65, in main
    states, infos = env.reset()
  File "/workspace/DunkCity/DunkCityDynasty-main/DunkCityDynasty/env/gym_env.py", line 21, in reset
    raw_states = self.external_env.reset()
  File "/workspace/DunkCity/DunkCityDynasty-main/DunkCityDynasty/env/base.py", line 74, in reset
    states = self._wait_for_state(min_player=3)
  File "/workspace/DunkCity/DunkCityDynasty-main/DunkCityDynasty/env/base.py", line 259, in _wait_for_state
    sleep(0.001)
  File "/workspace/DunkCity/DunkCityDynasty-main/DunkCityDynasty/utils/util_fn.py", line 16, in sleep
    pass
KeyboardInterrupt
```

Then I press ```Ctrl + C``` again to stop the process, the output is as follows:
```
Exception ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt:
```

After that, the process has been stopped.

In order to provide a complete overview of my actions, I've divided the errors into three parts as shown above. I've combined the entire error sequence (which is actually the amalgamation of the three parts above) below to present the complete errors.
```
0024:fixme:ntdll:create_logical_proc_info Improve CPU info reporting: system supports 48 logical cores, but only 32 supported!
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 33
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 34
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 35
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 36
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 37
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 38
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 39
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 40
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 41
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 42
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 43
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 44
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 45
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 46
0024:fixme:ntdll:create_logical_proc_info skipping logical processor 47
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
wine: failed to open "path-to-game-client/Lx33.exe": c0000135
^CTraceback (most recent call last):
  File "get_start.py", line 74, in <module>
    main()
  File "get_start.py", line 65, in main
    states, infos = env.reset()
  File "/workspace/DunkCity/DunkCityDynasty-main/DunkCityDynasty/env/gym_env.py", line 21, in reset
    raw_states = self.external_env.reset()
  File "/workspace/DunkCity/DunkCityDynasty-main/DunkCityDynasty/env/base.py", line 74, in reset
    states = self._wait_for_state(min_player=3)
  File "/workspace/DunkCity/DunkCityDynasty-main/DunkCityDynasty/env/base.py", line 259, in _wait_for_state
    sleep(0.001)
  File "/workspace/DunkCity/DunkCityDynasty-main/DunkCityDynasty/utils/util_fn.py", line 16, in sleep
    pass
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt:

```

I appreciate your time and attention in reviewing this issue. Please let me know if you need any further information from my side. I'm looking forward to your assistance and insights. Thank you!

**Comment by accuracy-maker** [comment]
my computer also is ubuntu 20.04, but when i run './install_deps.sh' , I got some errors: 'The following signatures couldn’t be verified because the public key is not available' and the download speed is very low. I want to know that have you ever see these errors?

**Comment by johnjim0816** [comment]
> client_path

client_path shoulg be right

**Comment by FuxiRL** [comment]
@sxzhuang 
Hi, I see your client_path in your config is still the default valule.
It should be changed to the path of the client in your computer.

    config = {
        'id': 1,
        'env_setting': 'linux',
        'client_path': 'path-to-game-client' -> your client path,
......
    }

Thank you.

**Comment by FuxiRL** [comment]
@accuracy-maker 
> my computer also is ubuntu 20.04, but when i run './install_deps.sh' , I got some errors: 'The following signatures couldn’t be verified because the public key is not available' and the download speed is very low. I want to know that have you ever see these errors?

Hi, for solving installing errors on Ubuntu, you can change the downloading source of your system, for example, using Tsinghua source or Alibaba source.

For the problem of slow download speed, there are some ways you can try:
1. Use a VPN (e.g., Shadowsocks、V2ray) to accelerate.
2. Access mirror site of huggingface, for example, https://mirrors.tuna.tsinghua.edu.cn/hugging-face-datasets/
When accessing the mirror site, you need to replace the domain name "huggingface.co" with the address of the mirror site in the data download link.
3. Connect your computer to a high-speed network, such as a 5G network. I have just tried this and it really worked (without a VPN).

**Comment by sxzhuang** [comment]
> @sxzhuang Hi, I see your client_path in your config is still the default valule. It should be changed to the path of the client in your computer.
> 
> ```
> config = {
>     'id': 1,
>     'env_setting': 'linux',
>     'client_path': 'path-to-game-client' -> your client path,
> ```
> 
> ...... }
> 
> Thank you.

I changed the path, and the error has been solved. Thanks a lot!!
